"""empty message

Revision ID: 59d195c5a5da
Revises: 0005
Create Date: 2026-04-22 13:56:25.115064+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59d195c5a5da'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_checkpoints_thread'), table_name='checkpoints')
    op.drop_index(op.f('idx_checkpoints_thread_ns'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('idx_checkpoint_writes_lookup'), table_name='checkpoint_writes')
    op.drop_index(op.f('idx_checkpoint_writes_thread'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.alter_column('agent_decisions', 'step_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_decisions', 'action_input',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_decisions', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('agent_decisions', 'cost_cents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_agent_decisions_festival'), table_name='agent_decisions')
    op.drop_index(op.f('idx_agent_decisions_thread'), table_name='agent_decisions')
    op.create_index(op.f('ix_agent_decisions_thread_id'), 'agent_decisions', ['thread_id'], unique=False)
    op.alter_column('agent_stream_events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_stream_events', 'usage',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('agent_stream_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_threads', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('agent_threads', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_threads', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_threads', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_threads', 'cost_cents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_threads', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_threads', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Drop dependent foreign key first, then the unique constraint
    op.drop_constraint('agent_stream_events_thread_id_fkey', 'agent_stream_events', type_='foreignkey')
    op.drop_constraint(op.f('agent_threads_thread_id_key'), 'agent_threads', type_='unique')
    op.create_index(op.f('ix_agent_threads_thread_id'), 'agent_threads', ['thread_id'], unique=True)
    # Recreate the foreign key to point to the new unique index
    op.create_foreign_key('agent_stream_events_thread_id_fkey', 'agent_stream_events', 'agent_threads', ['thread_id'], ['thread_id'])
    op.drop_column('agent_threads', 'cost_breakdown')
    op.alter_column('cost_logs', 'cost_cents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cost_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_cost_logs_created'), table_name='cost_logs')
    op.create_index('idx_cost_logs_created_at', 'cost_logs', ['created_at'], unique=False)
    op.create_foreign_key(None, 'cost_logs', 'festivals', ['festival_id'], ['id'])
    op.alter_column('discovery_queries', 'run_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('discovery_queries', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('discovery_queries', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('discovery_queries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_queries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_discovery_queries_category'), table_name='discovery_queries')
    op.alter_column('festival_event_dates', 'lineup',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('festival_event_dates', 'tickets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('festival_event_dates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('festival_event_dates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_event_dates_festival'), table_name='festival_event_dates')
    op.drop_constraint(op.f('festival_event_dates_festival_id_fkey'), 'festival_event_dates', type_='foreignkey')
    op.create_foreign_key(None, 'festival_event_dates', 'festivals', ['festival_id'], ['id'])
    op.add_column('festivals', sa.Column('failure_reason', sa.String(length=50), nullable=True))
    op.add_column('festivals', sa.Column('failure_message', sa.Text(), nullable=True))
    op.add_column('festivals', sa.Column('research_completeness_score', sa.Float(), nullable=True))
    op.alter_column('festivals', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'discovered'::character varying"))
    op.alter_column('festivals', 'state_changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('festivals', 'discovered_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('festivals', 'research_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('festivals', 'sync_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('festivals', 'is_duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('festivals', 'is_new_event_date',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('festivals', 'date_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('festivals', 'update_reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('festivals', 'existing_event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('festivals', 'discovery_cost_cents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('festivals', 'research_cost_cents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('festivals', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('festivals', 'validation_errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('festivals', 'validation_warnings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('festivals', 'error_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('festivals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('festivals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_festivals_clean_name'), table_name='festivals')
    op.drop_index(op.f('idx_festivals_created'), table_name='festivals')
    op.drop_index(op.f('idx_festivals_current_thread'), table_name='festivals')
    op.drop_index(op.f('idx_festivals_name'), table_name='festivals')
    op.drop_index(op.f('idx_festivals_partymap_event'), table_name='festivals')
    op.drop_index(op.f('idx_festivals_source'), table_name='festivals')
    op.drop_index(op.f('idx_festivals_state'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_error_category'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_quarantined_at'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_retry_count'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_update_required'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_validation_checked_at'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_validation_status'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_workflow_type'), table_name='festivals')
    op.create_index(op.f('ix_festivals_clean_name'), 'festivals', ['clean_name'], unique=False)
    op.create_index(op.f('ix_festivals_current_thread_id'), 'festivals', ['current_thread_id'], unique=False)
    op.create_index(op.f('ix_festivals_failure_reason'), 'festivals', ['failure_reason'], unique=False)
    op.create_index(op.f('ix_festivals_name'), 'festivals', ['name'], unique=False)
    op.create_index(op.f('ix_festivals_partymap_event_id'), 'festivals', ['partymap_event_id'], unique=False)
    op.create_index(op.f('ix_festivals_source'), 'festivals', ['source'], unique=False)
    op.create_index(op.f('ix_festivals_state'), 'festivals', ['state'], unique=False)
    op.alter_column('job_activity', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('job_activity', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_job_activity_created_at'), 'job_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_activity_job_type'), 'job_activity', ['job_type'], unique=False)
    op.alter_column('name_mappings', 'use_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('name_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('name_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('name_mappings_raw_name_key'), 'name_mappings', type_='unique')
    op.create_index(op.f('ix_name_mappings_normalized_raw'), 'name_mappings', ['normalized_raw'], unique=False)
    op.create_index(op.f('ix_name_mappings_raw_name'), 'name_mappings', ['raw_name'], unique=False)
    op.alter_column('pipeline_schedules', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_schedules', 'hour',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('pipeline_schedules', 'minute',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_schedules', 'run_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('pipeline_schedules_task_type_key'), 'pipeline_schedules', type_='unique')
    op.create_index(op.f('ix_pipeline_schedules_task_type'), 'pipeline_schedules', ['task_type'], unique=True)
    op.alter_column('refresh_approvals', 'current_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('refresh_approvals', 'proposed_changes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('refresh_approvals', 'change_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('refresh_approvals', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('refresh_approvals', 'research_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('refresh_approvals', 'research_sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('refresh_approvals', 'auto_approve_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.85'::double precision"))
    op.alter_column('refresh_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_approvals', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("(now() + '7 days'::interval)"))
    op.create_index(op.f('ix_refresh_approvals_created_at'), 'refresh_approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_approvals_event_date_id'), 'refresh_approvals', ['event_date_id'], unique=False)
    op.create_index(op.f('ix_refresh_approvals_event_id'), 'refresh_approvals', ['event_id'], unique=False)
    op.create_index(op.f('ix_refresh_approvals_status'), 'refresh_approvals', ['status'], unique=False)
    op.alter_column('state_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_state_transitions_festival'), table_name='state_transitions')
    op.drop_constraint(op.f('state_transitions_festival_id_fkey'), 'state_transitions', type_='foreignkey')
    op.create_foreign_key(None, 'state_transitions', 'festivals', ['festival_id'], ['id'])
    op.alter_column('system_settings', 'value_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'string'::character varying"))
    op.alter_column('system_settings', 'editable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('system_settings', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('system_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('system_settings_key_key'), 'system_settings', type_='unique')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_unique_constraint(op.f('system_settings_key_key'), 'system_settings', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('system_settings', 'editable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('system_settings', 'value_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'string'::character varying"))
    op.drop_constraint(None, 'state_transitions', type_='foreignkey')
    op.create_foreign_key(op.f('state_transitions_festival_id_fkey'), 'state_transitions', 'festivals', ['festival_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_state_transitions_festival'), 'state_transitions', ['festival_id'], unique=False)
    op.alter_column('state_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_refresh_approvals_status'), table_name='refresh_approvals')
    op.drop_index(op.f('ix_refresh_approvals_event_id'), table_name='refresh_approvals')
    op.drop_index(op.f('ix_refresh_approvals_event_date_id'), table_name='refresh_approvals')
    op.drop_index(op.f('ix_refresh_approvals_created_at'), table_name='refresh_approvals')
    op.alter_column('refresh_approvals', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("(now() + '7 days'::interval)"))
    op.alter_column('refresh_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_approvals', 'auto_approve_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.85'::double precision"))
    op.alter_column('refresh_approvals', 'research_sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('refresh_approvals', 'research_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('refresh_approvals', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('refresh_approvals', 'change_summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('refresh_approvals', 'proposed_changes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('refresh_approvals', 'current_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_pipeline_schedules_task_type'), table_name='pipeline_schedules')
    op.create_unique_constraint(op.f('pipeline_schedules_task_type_key'), 'pipeline_schedules', ['task_type'], postgresql_nulls_not_distinct=False)
    op.alter_column('pipeline_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_schedules', 'run_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_schedules', 'minute',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pipeline_schedules', 'hour',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('pipeline_schedules', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_name_mappings_raw_name'), table_name='name_mappings')
    op.drop_index(op.f('ix_name_mappings_normalized_raw'), table_name='name_mappings')
    op.create_unique_constraint(op.f('name_mappings_raw_name_key'), 'name_mappings', ['raw_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('name_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('name_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('name_mappings', 'use_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_job_activity_job_type'), table_name='job_activity')
    op.drop_index(op.f('ix_job_activity_created_at'), table_name='job_activity')
    op.alter_column('job_activity', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_activity', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_festivals_state'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_source'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_partymap_event_id'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_name'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_failure_reason'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_current_thread_id'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_clean_name'), table_name='festivals')
    op.create_index(op.f('ix_festivals_workflow_type'), 'festivals', ['workflow_type'], unique=False)
    op.create_index(op.f('ix_festivals_validation_status'), 'festivals', ['validation_status'], unique=False)
    op.create_index(op.f('ix_festivals_validation_checked_at'), 'festivals', ['validation_checked_at'], unique=False)
    op.create_index(op.f('ix_festivals_update_required'), 'festivals', ['update_required'], unique=False)
    op.create_index(op.f('ix_festivals_retry_count'), 'festivals', ['retry_count'], unique=False)
    op.create_index(op.f('ix_festivals_quarantined_at'), 'festivals', ['quarantined_at'], unique=False)
    op.create_index(op.f('ix_festivals_error_category'), 'festivals', ['error_category'], unique=False)
    op.create_index(op.f('idx_festivals_state'), 'festivals', ['state'], unique=False)
    op.create_index(op.f('idx_festivals_source'), 'festivals', ['source'], unique=False)
    op.create_index(op.f('idx_festivals_partymap_event'), 'festivals', ['partymap_event_id'], unique=False)
    op.create_index(op.f('idx_festivals_name'), 'festivals', ['name'], unique=False)
    op.create_index(op.f('idx_festivals_current_thread'), 'festivals', ['current_thread_id'], unique=False)
    op.create_index(op.f('idx_festivals_created'), 'festivals', ['created_at'], unique=False)
    op.create_index(op.f('idx_festivals_clean_name'), 'festivals', ['clean_name'], unique=False)
    op.alter_column('festivals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('festivals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('festivals', 'error_context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('festivals', 'validation_warnings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('festivals', 'validation_errors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('festivals', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('festivals', 'research_cost_cents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('festivals', 'discovery_cost_cents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('festivals', 'existing_event_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('festivals', 'update_reasons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('festivals', 'date_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('festivals', 'is_new_event_date',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('festivals', 'is_duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('festivals', 'sync_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('festivals', 'research_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('festivals', 'discovered_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('festivals', 'state_changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('festivals', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'discovered'::character varying"))
    op.drop_column('festivals', 'research_completeness_score')
    op.drop_column('festivals', 'failure_message')
    op.drop_column('festivals', 'failure_reason')
    op.drop_constraint(None, 'festival_event_dates', type_='foreignkey')
    op.create_foreign_key(op.f('festival_event_dates_festival_id_fkey'), 'festival_event_dates', 'festivals', ['festival_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_event_dates_festival'), 'festival_event_dates', ['festival_id'], unique=False)
    op.alter_column('festival_event_dates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('festival_event_dates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('festival_event_dates', 'tickets',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('festival_event_dates', 'lineup',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.create_index(op.f('idx_discovery_queries_category'), 'discovery_queries', ['category'], unique=False)
    op.alter_column('discovery_queries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_queries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_queries', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('discovery_queries', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('discovery_queries', 'run_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'cost_logs', type_='foreignkey')
    op.drop_index('idx_cost_logs_created_at', table_name='cost_logs')
    op.create_index(op.f('idx_cost_logs_created'), 'cost_logs', ['created_at'], unique=False)
    op.alter_column('cost_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_logs', 'cost_cents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('agent_threads', sa.Column('cost_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    # Drop foreign key first, then index, then recreate unique constraint
    op.drop_constraint('agent_stream_events_thread_id_fkey', 'agent_stream_events', type_='foreignkey')
    op.drop_index(op.f('ix_agent_threads_thread_id'), table_name='agent_threads')
    op.create_unique_constraint(op.f('agent_threads_thread_id_key'), 'agent_threads', ['thread_id'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key('agent_stream_events_thread_id_fkey', 'agent_stream_events', 'agent_threads', ['thread_id'], ['thread_id'])
    op.alter_column('agent_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_threads', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_threads', 'result_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_threads', 'cost_cents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_threads', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_threads', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_threads', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_threads', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('agent_stream_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_stream_events', 'usage',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('agent_stream_events', 'event_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_agent_decisions_thread_id'), table_name='agent_decisions')
    op.create_index(op.f('idx_agent_decisions_thread'), 'agent_decisions', ['thread_id'], unique=False)
    op.create_index(op.f('idx_agent_decisions_festival'), 'agent_decisions', ['festival_id'], unique=False)
    op.alter_column('agent_decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_decisions', 'cost_cents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_decisions', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('agent_decisions', 'action_input',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_decisions', 'step_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('idx_checkpoint_writes_thread'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_index(op.f('idx_checkpoint_writes_lookup'), 'checkpoint_writes', ['thread_id', 'checkpoint_ns', 'checkpoint_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('idx_checkpoints_thread_ns'), 'checkpoints', ['thread_id', 'checkpoint_ns'], unique=False)
    op.create_index(op.f('idx_checkpoints_thread'), 'checkpoints', ['thread_id'], unique=False)
    # ### end Alembic commands ###
