"""Add missing indexes for foreign keys and created_at

Revision ID: d2842265e225
Revises: 59d195c5a5da
Create Date: 2026-04-24 00:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd2842265e225'
down_revision: Union[str, None] = '59d195c5a5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_decisions_festival_id'), 'agent_decisions', ['festival_id'], unique=False)
    op.create_index(op.f('ix_festival_event_dates_festival_id'), 'festival_event_dates', ['festival_id'], unique=False)
    op.create_index(op.f('ix_festivals_created_at'), 'festivals', ['created_at'], unique=False)
    op.create_index(op.f('ix_state_transitions_festival_id'), 'state_transitions', ['festival_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_transitions_festival_id'), table_name='state_transitions')
    op.drop_index(op.f('ix_festivals_created_at'), table_name='festivals')
    op.drop_index(op.f('ix_festival_event_dates_festival_id'), table_name='festival_event_dates')
    op.drop_index(op.f('ix_agent_decisions_festival_id'), table_name='agent_decisions')
    # ### end Alembic commands ###
